theme: vonge
title: Itzel's Blog
author: igonz044
email: itzel.1223@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I will be writing about Web Design in this blog.

# social links
linkedin_username: your-linkedin-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

